#!/usr/bin/env node
// ---------------------------------------------------------------------------
// v11 SC-00 — the launch control plane CLI.
//
//   node backend/scripts/launch-state.js verify   document integrity (CI-safe)
//   node backend/scripts/launch-state.js gate     integrity + GO/NO-GO verdict
//   node backend/scripts/launch-state.js render   regenerate docs/LAUNCH_STATE.md
//
// `verify` answers "can this document be believed?" and must stay green on
// every push. `gate` answers "may we ship?" and stays red until the evidence
// exists — that is the point of it, not a fault.
//
// Read-only apart from `render`. Touches no external system, runs no migration
// and prints no secret.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const {
  integrityProblems,
  computeVerdicts,
  CHECK_PASSING,
  EVIDENCE_PASSING,
} = require('../lib/launch-state');

const ROOT = path.join(__dirname, '..', '..');
const STATE_PATH = path.join(ROOT, 'docs', 'launch', 'launch-state.json');
const RENDER_PATH = path.join(ROOT, 'docs', 'LAUNCH_STATE.md');

// The banner every superseded document must carry, so a reader who opens the
// old file directly cannot mistake it for current truth.
const SUPERSEDED_MARKER = '> **SUPERSEDED';

function loadState(file = STATE_PATH) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function headSha() {
  if (process.env.GITHUB_SHA) return process.env.GITHUB_SHA;
  try { return execSync('git rev-parse HEAD', { encoding: 'utf8', cwd: ROOT }).trim(); }
  catch { return null; }
}

// Integrity checks that need the filesystem, kept out of the pure module:
// the manifest's claims about other documents must actually hold on disk.
function documentProblems(state, root = ROOT) {
  const problems = [];
  for (const doc of state.superseded_documents || []) {
    const p = path.join(root, doc.path);
    if (!fs.existsSync(p)) { problems.push(`superseded document missing: ${doc.path}`); continue; }
    const body = fs.readFileSync(p, 'utf8');
    if (!body.includes(SUPERSEDED_MARKER)) {
      problems.push(`${doc.path} is listed as superseded but carries no SUPERSEDED banner — two active documents can disagree`);
    }
  }

  // Migration count is a fact about the repository, so it is verified against
  // the repository rather than trusted.
  const migDir = path.join(root, 'backend', 'migrations');
  if (fs.existsSync(migDir)) {
    const onDisk = fs.readdirSync(migDir).filter((f) => f.endsWith('.sql')).length;
    const claimed = state.migrations && state.migrations.on_disk_count;
    if (claimed != null && claimed !== onDisk) {
      problems.push(`migrations.on_disk_count says ${claimed}, backend/migrations holds ${onDisk}`);
    }
  }
  return problems;
}

// --- render ---------------------------------------------------------------

const STATUS_LABEL = {
  not_run: 'not run',
  skipped: 'SKIPPED',
  failed: 'FAILED',
  passed_locally: 'passed locally',
  passed_ci: 'passed in CI',
  configured: 'configured',
  live_rehearsed: 'live rehearsed',
  observed: 'observed',
  unknown: 'UNKNOWN',
};
const label = (s) => STATUS_LABEL[s] || s;
const mark = (ok) => (ok ? 'yes' : 'no');

function render(state, observed) {
  const v = computeVerdicts(state, observed);
  const c = state.candidate || {};
  const out = [];
  const p = (s = '') => out.push(s);

  p('# Scalvya — launch state');
  p();
  p('> Generated from `docs/launch/launch-state.json` by `npm run launch:render`.');
  p('> Do not edit this file by hand; edit the JSON and regenerate. Any other');
  p('> release document that disagrees with this one is superseded, not a');
  p('> second opinion.');
  p();
  p(`Repository \`${state.repository}\` · branch \`${c.branch}\` · generated ${state.generated_at_utc}`);
  p();

  p('## Verdict');
  p();
  p('| Track | Verdict | Why |');
  p('|---|---|---|');
  for (const track of ['capped_beta', 'public_paid']) {
    const reasons = v[track].reasons.length ? v[track].reasons.join('; ') : 'all conditions met';
    p(`| ${track === 'capped_beta' ? 'Capped beta' : 'Public paid launch'} | **${v[track].verdict}** | ${reasons} |`);
  }
  p();
  p('A capped, supported beta and an unrestricted public paid launch are');
  p('different risk decisions and are decided separately.');
  p();

  p('## Release candidate');
  p();
  if (!c.sha) {
    p(`**No candidate is pinned.** ${c.explanation || ''}`);
    p();
    p(`- Reviewed baseline: \`${c.baseline_sha}\``);
    p(`- HEAD when this record was written: \`${c.head_at_generation}\``);
  } else {
    p(`- Candidate SHA: \`${c.sha}\` (${c.state})`);
    p(`- HEAD now: \`${observed.head_sha || 'unknown'}\`${observed.head_sha && observed.head_sha !== c.sha ? ' — **drifted, candidate is stale**' : ''}`);
    p(`- Bundle: ${(c.bundle && c.bundle.files || []).join(', ') || 'not built'}`);
  }
  p(`- Environment class: ${c.environment_class}`);
  p();
  if ((state.drift_from_baseline || []).length) {
    p('### Drift from the reviewed baseline');
    p();
    p('| Commit | Subject | Already closes |');
    p('|---|---|---|');
    for (const d of state.drift_from_baseline) p(`| \`${d.sha}\` | ${d.subject} | ${d.closes_requirement} |`);
    p();
  }

  p('## Migrations');
  p();
  const av = (state.migrations && state.migrations.applied_verification) || {};
  p(`- On disk: ${state.migrations.on_disk_count} files, range ${state.migrations.range}. ${state.migrations.on_disk_note || ''}`);
  p(`- **Applied to the database: ${label(av.status)}** — source \`${av.source}\`, last run ${av.last_run_utc || 'never recorded'}.`);
  if (av.contradiction) { p(); p(`  ${av.contradiction}`); }
  if (av.owner_action) { p(); p(`  *Owner action:* ${av.owner_action}`); }
  p();
  p('Presence in `backend/migrations` is not applied-ness. `release-check`');
  p('reads the filesystem and never connects to a database, so it can never');
  p('settle this question.');
  p();

  p('## Required checks');
  p();
  p('| Check | Command | Status | At SHA | Counts as passed |');
  p('|---|---|---|---|---|');
  for (const ch of state.checks || []) {
    p(`| ${ch.name}${ch.required ? '' : ' *(optional)*'} | \`${ch.command}\` | ${label(ch.status)} | ${ch.observed_at_sha ? `\`${ch.observed_at_sha.slice(0, 7)}\`` : '—'} | ${mark(CHECK_PASSING.includes(ch.status))} |`);
  }
  p();

  p('## Owner evidence');
  p();
  p('Claude Code cannot produce any of these: they require live Stripe, Resend,');
  p('Supabase or production configuration access.');
  p();
  p('| Evidence | Status | Required for | Runbook |');
  p('|---|---|---|---|');
  for (const e of state.owner_evidence || []) {
    p(`| ${e.title} | ${label(e.status)}${EVIDENCE_PASSING.includes(e.status) ? '' : ' — **outstanding**'} | ${(e.required_for || []).join(', ')} | \`${e.runbook}\` |`);
  }
  p();

  p('## Open blockers');
  p();
  const open = (state.blockers || []).filter((b) => b.status === 'open');
  if (!open.length) p('None.');
  else {
    p('| Severity | Blocker | Owner | Closure |');
    p('|---|---|---|---|');
    for (const b of open) p(`| ${b.severity} | ${b.title} | ${b.owner} | ${b.closure} |`);
  }
  p();

  p('## Rollback');
  p();
  for (const [k, val] of Object.entries(state.rollback || {})) p(`- **${k}:** ${val}`);
  p();

  p('## Superseded documents');
  p();
  p('These remain in the repository as history. None of them is current truth.');
  p();
  for (const d of state.superseded_documents || []) p(`- \`${d.path}\` — ${d.reason}`);
  p();

  p('## Creating a new candidate');
  p();
  for (const step of state.how_to_create_a_new_candidate || []) p(`${step.startsWith('Any commit') ? '\n' : ''}${step}`);
  p();

  return out.join('\n');
}

// --- CLI ------------------------------------------------------------------

function main() {
  const mode = process.argv[2] || 'verify';
  const state = loadState();
  const observed = { head_sha: headSha() };

  const problems = [...integrityProblems(state), ...documentProblems(state)];

  if (mode === 'render') {
    if (problems.length) {
      console.error('Refusing to render an untrustworthy launch state:');
      for (const p of problems) console.error(`  - ${p}`);
      process.exit(1);
    }
    fs.writeFileSync(RENDER_PATH, render(state, observed), 'utf8');
    console.log(`Wrote ${path.relative(ROOT, RENDER_PATH)}`);
    process.exit(0);
  }

  if (mode === 'verify') {
    if (problems.length) {
      console.error('\nLaunch-state integrity: FAILED\n');
      for (const p of problems) console.error(`  - ${p}`);
      console.error('');
      process.exit(1);
    }
    console.log('\nLaunch-state integrity: OK — one active launch truth, evidence pinned, verdict recomputed.\n');
    process.exit(0);
  }

  if (mode === 'gate') {
    const v = computeVerdicts(state, observed);
    console.log('\nLaunch gate\n');
    if (problems.length) {
      console.log('  Integrity: FAILED');
      for (const p of problems) console.log(`    - ${p}`);
    } else {
      console.log('  Integrity: OK');
    }
    for (const track of ['capped_beta', 'public_paid']) {
      console.log(`\n  ${track}: ${v[track].verdict}`);
      for (const r of v[track].reasons) console.log(`    - ${r}`);
    }
    console.log('');
    const go = !problems.length && v.capped_beta.verdict === 'GO' && v.public_paid.verdict === 'GO';
    process.exit(go ? 0 : 1);
  }

  console.error(`Unknown mode: ${mode}. Use verify | gate | render.`);
  process.exit(2);
}

if (require.main === module) main();

module.exports = { loadState, documentProblems, render, headSha, SUPERSEDED_MARKER };
