import { Link, useParams } from 'react-router-dom';
import { BRAND, LEGAL_VERSION } from '../brand';

// Prompt 14: legal pages. Content is a reviewed-by-counsel PLACEHOLDER — the
// bracketed items must be confirmed before a public launch.
const SUPPORT = BRAND.supportEmail;

const DOCS = {
  terms: {
    title: 'Terms of Service',
    body: [
      ['Agreement', `By using ${BRAND.name} you agree to these Terms. If you do not agree, do not use the service. ${BRAND.name} is operated by ${BRAND.legalName}.`],
      ['The service', `${BRAND.name} is an AI marketing workspace that generates positioning, offers and marketing assets from the information you provide. Output is AI-generated and provided "as is" — see the AI Disclaimer.`],
      ['Your account', 'You are responsible for keeping your login secure and for activity under your account. You must provide a valid email and accept these Terms and the Privacy Policy at signup.'],
      ['Acceptable use', 'Do not use the service to generate unlawful, misleading, or harmful content, to infringe others’ rights, or to attempt to break, overload or reverse-engineer the service.'],
      ['Plans & billing', 'Paid plans start with a 3-day free trial that requires a payment method; you are charged when the trial ends unless you cancel. See the Refund & Cancellation Policy.'],
      ['Termination', 'You may delete your account at any time from Account → Data. We may suspend accounts that violate these Terms.'],
      ['Liability', `[PLACEHOLDER — counsel to confirm limitation of liability and warranty disclaimers.] To the extent permitted by law, ${BRAND.name} is not liable for indirect or consequential damages, or for business decisions made based on AI output.`],
      ['Changes', `We may update these Terms; material changes will be posted here with a new version date. Current version: ${LEGAL_VERSION}.`],
      ['Contact', `Questions: ${SUPPORT}.`],
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    body: [
      ['What we collect', 'Account data (email), the business information you enter, generated assets, usage/metering events, and billing status (via Stripe). We do not sell your data.'],
      ['How we use it', 'To provide the service (generate and store your assets), enforce plan limits, process payments, send transactional email, and improve reliability.'],
      ['AI processing', `The information you enter is sent to our AI provider (Anthropic) to generate output. Do not enter data you are not permitted to share.`],
      ['Subprocessors', 'We rely on: Vercel (hosting), Supabase (database & authentication), Anthropic (AI generation), Stripe (payments), and Resend (transactional email). Each processes data only to provide their part of the service.'],
      ['Your rights', 'You can export all of your data or delete your account and its data at any time from Account → Data. [PLACEHOLDER — counsel to confirm GDPR/CCPA-specific rights and data-retention periods.]'],
      ['Data retention', 'We keep your data while your account is active. On deletion we remove your workspace data and authentication record; we retain only records legally required (e.g. payment records held by Stripe).'],
      ['Contact', `Privacy questions: ${SUPPORT}. Current version: ${LEGAL_VERSION}.`],
    ],
  },
  cookies: {
    title: 'Cookie Notice',
    body: [
      ['Essential cookies only', `${BRAND.name} uses only strictly-necessary cookies to keep you signed in (secure, HttpOnly session cookies). These are required for the app to work and are not used for advertising.`],
      ['No tracking cookies', 'We do not currently set analytics or marketing cookies. If that changes, we will ask for consent first and update this notice.'],
      ['Contact', `Questions: ${SUPPORT}.`],
    ],
  },
  'ai-disclaimer': {
    title: 'AI Output Disclaimer',
    body: [
      ['AI-generated content', `Assets produced by ${BRAND.name} are generated by AI from the information you provide. They are a starting point, not professional advice.`],
      ['Review before use', 'Always review and edit output before publishing. AI can be inaccurate, omit facts, or produce claims that need verification. You are responsible for what you publish.'],
      ['No guarantees', 'We make no promise of specific revenue, results, or outcomes. Nothing generated is legal, financial, medical, or tax advice.'],
      ['Contact', `Questions: ${SUPPORT}.`],
    ],
  },
  refund: {
    title: 'Refund & Cancellation Policy',
    body: [
      ['Free trial', 'Paid plans begin with a 3-day free trial. You can cancel any time during the trial from Account → Billing and you will not be charged.'],
      ['After the trial', 'When the trial ends your card is charged for the plan you chose. Subscriptions renew automatically until cancelled.'],
      ['Cancelling', 'Cancel any time; your plan stays active until the end of the current billing period. You keep access to your data.'],
      ['Refunds', '[PLACEHOLDER — counsel to confirm refund terms and any statutory cooling-off rights.] Contact us and we will review refund requests case by case.'],
      ['Contact', `Billing questions: ${SUPPORT}.`],
    ],
  },
};

export default function Legal() {
  const { slug } = useParams();
  const doc = DOCS[slug];

  if (!doc) {
    return (
      <div className="legal">
        <div className="legal-card">
          <h1>Not found</h1>
          <p>That document doesn&apos;t exist.</p>
          <p><Link to="/">Back home</Link></p>
        </div>
      </div>
    );
  }

  return (
    <div className="legal">
      <div className="legal-card">
        <p className="legal-back"><Link to="/">&larr; {BRAND.name}</Link></p>
        <h1>{doc.title}</h1>
        <p className="legal-meta">Version {LEGAL_VERSION}</p>
        {doc.body.map(([heading, text]) => (
          <section key={heading}>
            <h2>{heading}</h2>
            <p>{text}</p>
          </section>
        ))}
        <hr />
        <p className="legal-links">
          <Link to="/legal/terms">Terms</Link> &middot;{' '}
          <Link to="/legal/privacy">Privacy</Link> &middot;{' '}
          <Link to="/legal/cookies">Cookies</Link> &middot;{' '}
          <Link to="/legal/ai-disclaimer">AI Disclaimer</Link> &middot;{' '}
          <Link to="/legal/refund">Refunds</Link>
        </p>
      </div>
    </div>
  );
}
